# Generated by Django 3.2.4 on 2021-07-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
