# Generated by Django 3.2.3 on 2021-07-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210721_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='admission_fee',
            field=models.CharField(default='$5.00', max_length=100),
        ),
    ]
