# Generated by Django 3.2.3 on 2021-07-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_event_admission_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='age_rating',
            field=models.CharField(choices=[('General Admission', 'General Admission'), ('Teens 13+', 'Teens 13+'), ('Adults 18+', 'Adults 18+'), ('Adults 21+', 'Adults 21+')], default='General Admission', max_length=50, verbose_name='Age Rating'),
        ),
        migrations.AlterField(
            model_name='event',
            name='covid_protocol',
            field=models.CharField(choices=[('Nothing Specified', 'Nothing Specified'), ('Vaccination Required', 'Vaccination Required'), ('Mask Required Indoors', 'Mask Required Indoors'), ('Vaccination and Masks Required Indoors', 'Vaccination and Masks Required Indoors')], default='Nothing Specified', max_length=50, verbose_name='Covid Protocol'),
        ),
    ]
